#
###################################
# Site wide configuration
####################################
#
title: ANSIanggoro
email: ansianggoro@gmail.com
description: Hungry
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Jakarta
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: ansi anggoro
  avatar: profile-logo.png
  job: " "
  bio: "Wonderer And  A Wanderer"
  email: ansianggoro@gmail.com
  disqus-shortname: ncanggoro
  github: NCanggoro
  rss: Subscribe
